### ISSUE TITLE
Using Home and End keys in text input inserts undefined as a string

### ISSUE THREAD

**Issue by timfish** [huochunpeng/makes#10]
- Run `npx makes aurelia`
- When asked for a project name, hit the Home or End key

Result
![image](https://user-images.githubusercontent.com/1150298/89523041-2281dd80-d7da-11ea-8454-547559f1f799.png)

**Comment by 3cp** [comment]
What terminal? On my mac terminal, home and end keys are captured by terminal to scroll to the top and bottom.

**Comment by timfish** [comment]
This occurs with the default Windows command prompt and also [cmder](https://cmder.net/) which is based on [ConEmu](https://conemu.github.io/).
