### ISSUE TITLE
Support scaffolding from npm package

### ISSUE THREAD

**Issue by Eagle94T** [huochunpeng/makes#12]
At the moment installations from Bitbucket, Github and Gitlab are possible, what about supporting installation from npm-packages?
So you can have a repo with tests etc. inside it and build/publish it without the test sources etc., so just the relevant stuff is downloaded for the makes process.

**Comment by 3cp** [comment]
When I was designing "makes", I deliberately avoided npm package to lower user's burden. Furthermore, I also experienced surprising edge case in **old version of aurelia-cli** (which publishes skeletons inside the npm package): npm package by default ignores some files, for example `.gitignore` file which you provided inside your skeleton. There are probably few other files ignored by npm package by default. Those edge cases could surprise skeleton authors big time, for this reason I am reluctant to add support of npm package. https://github.com/aurelia/cli/commit/d13c437a26fd5b6b0043f8b0ee8738806da66a26

I will keep this request in mind, if in future I was convinced to add it, I would also add doc for all edge cases. 

By default, "makes" targets the skeleton git repo's default branch (which is master by git default). You could setup your dev flow to always use PR to default branch, where PR will ensure all tests passed before merging.

> so just the relevant stuff is downloaded for the makes process.

I can understand, this is a valid point. At least for now, those test files are not big for dumberjs/new, aurelia/v1 and aurelia/new skeletons.

**Comment by Eagle94T** [comment]
@3cp thanks for the further information since it works with gitlab repository, the current state is fine for me. Therefore, we can close the issue.
