### ISSUE TITLE
Question: reason for not allowing '.' in the project name

### ISSUE THREAD

**Issue by arnederuwe** [huochunpeng/makes#13]
When using `makes` to scaffold a new Aurelia 2 app, you can't use the `.` char in the project name.
What's the reason for this? Does it break something I'm not aware of?

We mostly set up our smaller Aurelia projects like this:
- MyApp.Api (.net core)
- MyApp.Business (.net standard)
- MyApp.Client (Aurelia)

**Comment by 3cp** [comment]
I couldn't think of a reason either :-)
It was just a very conservative selection of allowed characters. Will add "." soon.

In the meantime, you can manually create the folder then run `npx makes aurelia --here` within.
