### ISSUE TITLE
Feature Request to replace fileName dynamically

### ISSUE THREAD

**Issue by Eagle94T** [huochunpeng/makes#15]
# Feature Request

I would ask for a new feature to be able to use the response of a question as a file-name. Currently only hard-coded file-names are possible.

As syntax I would suggest to stay as close to the existing logic in the files, e.g. `echo_myQuestion` and this would be replaced with the answer of the question.

However, the posibility to only replacing a part of the filename should also be given, e.g. `echo_myQuestion.ts` or `aPrefix_echo_myQuestion.ts`

If the fileName replacing is made before the if/else conditions, it should even be possible to use the file conditionally, e.g. `echo_myQuestion.ts_if_plugin

**Comment by 3cp** [comment]
This is doable right now in after.js file.

The before.js and after.js made wide range of customization possible.

Inside after.js, you can rewrite vinyl file name and/or extension before "makes" writes the file. So you can just put some placeholder file in the skeleton to be modified later in after.js.

You can even create vinyl file, or merge vinyl files in after.js. It's just like what you can do in a gulp plugin, it's all about transforming a stream of vinyl file objects.

Let me know if you need help after reading the document. Good luck!

**Comment by 3cp** [comment]
Sorry, it's not after.js, it's transform.js.
I almost forgot the details :-) I have not touched a skeleton repo for a while.

**Comment by Eagle94T** [comment]
Thanks for the quick response. Seems I didn't look good enough at the documentation 🙈 
But it doesn't seem to hard to make that transformation 👍🏽
