### ISSUE TITLE
I would like to help, yes

### ISSUE THREAD

**Issue by adriatic** [huochunpeng/makes#2]
Hi @3cp 

Rob set me up to be able to experiment with using Aurelia 2 to create a few prototypes of the app I am very excited to do (Aurelia integration with WordPress, by creating the Aurelia front end for WordPress Content Management System). This integration is way too big for me alone, so I only want to do as much as it needed to find a few other people with this same interest.

This brings me to makes tool that looks very promising (I am circling around such tool forever), so when Rob mentioned that I might help "anywhere" around makes, I liked his comment a lot.

A few questions:

1. would you care if I help you (assuming that I really can help, as I do not know what do you need)?

2. for my own education, I want to create all other variants of the **[original collection](https://github.com/aurelia/aurelia/tree/master/examples)**

3. In order to be able to so 2. above, I would like to learn everything I can about **[makes](https://github.com/aurelia/new)**.

4. After being done with 2. and 3. I would like to document makes and all examples I will create.

**Comment by 3cp** [comment]
No, thanks. Makes is documented, and all other variants of the original collection are duplicated in aurelia/new skeletons (if you ever read the readme of aurelia/new, it tells you why parcel/browserify/fusebox setups are disabled right now).

My previous github username was huochunpeng before I renamed it to a shorter version. The last time we had conversation was the final heated arguments in AUCS gitter channel more than a year ago. We had totally different view/approach on any tech related thing. Same as many other developers (this should not surprise you), I have no interest to work with you in any condition, my position has not changed.

I understand you are passionate to help in OSS world, which I appreciate in principle. But I personally don't think you are in a position that can offer help on coding or design or document stuff you don't quite understand. Neither I have energy or interest to help you to become a decent coder.

Of course I sound very mean. But I just don't enjoy spending energy to have any further conversation with you after our exchange in AUCS. I am a coder in free unpaid OSS land, we seek and talk with our same species. Coder can draw my interest with a single line of code, your lengthy talks could not.

As my parents always try to teach my little son how to pronounce English words, I always remind them, "I love you, but please please don't offer help on a language you don't even speak.".

**Comment by adriatic** [comment]
Thanks for clarifying your position.
