### ISSUE TITLE
Failed a simple attempt to use makes

### ISSUE THREAD

**Issue by adriatic** [huochunpeng/makes#3]
@3cp,

As I know nothing about `makes` (other than what is documented in its**[README](https://github.com/aurelia/new#aurelia-2-scaffolding-skeleton)** I tried to invoke it with 

```
λ npx makes test1
```
expecting to get a project skeleton in the local folder **`test1`**. Here is what I did get:
```
λ npx makes test1
npx: installed 1 in 1.23s
makes v0.12.0
[makes] Using remote skeleton github:test1/new
[makes] Unable to get https://codeload.github.com/test1/new/tar.gz/master
[makes] Maybe this is a private skeleton.
[makes] preparing skeleton: git clone git@github.com:test1/new.git github.com-test1-new
Cloning into 'github.com-test1-new'...
Warning: Permanently added the RSA host key for IP address '140.82.114.3' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Error: git exit code: 128
    at ChildProcess.<anonymous> (C:\Users\nik\AppData\Roaming\npm-cache\_npx\1788\node_modules\makes\dist\index.js:19224:16)
    at ChildProcess.emit (events.js:203:13)
    at ChildProcess.cp.emit (C:\Users\nik\AppData\Roaming\npm-cache\_npx\1788\node_modules\makes\dist\index.js:19150:29)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)

c:\work\learning\makes
```

So, it seems that `makes` assumes the existence of the remote GitHub repository `github:test1/new`, when I supply `new` as the only argument. where I expected to create a local folder in the current directory,. changing `test1` to `aurelia`, things are a lot more meaningful:

```
λ npx makes aurelia
npx: installed 1 in 1.611s
makes v0.12.0
[makes] Using remote skeleton github:aurelia/new
[makes] Fetching tarball https://codeload.github.com/aurelia/new/tar.gz/master
? Please name this new project: » my-app
```

The line `Fetching tarball https://codeload.github.com/aurelia/new/tar.gz/master` seems to add Aurelia binaries from Github, instead of fetching it from npm. 

My conclusion is that the `makes` tool is highly specialized for Aurelia core developers - and I need the application developers version.

Obviously, `makes` is your baby and you likely plan to make it a tool that supports both groups of developers. Please see if the variant where you extend its design and I write the implementation looks appealing to you.

**Comment by 3cp** [comment]
Read readme on this repo. There is a link to full documentation.

**Comment by adriatic** [comment]
Should have found that document myself. Thank you.
