### ISSUE TITLE
Unable to use number 0 (zero) in project name.

### ISSUE THREAD

**Issue by atpw25** [huochunpeng/makes#4]
Example: 

```
$ npx makes dumberjs
npx: installed 1 in 0.875s
makes v0.14.0 https://makes.js.org
[makes] Using remote skeleton github:dumberjs/new
[makes] Fetching tarball https://codeload.github.com/dumberjs/new/tar.gz/master
? Please name this new project: › test0
› Please only use letters, numbers, dash(-) and underscore(_).
```

Maybe caused by the following? (should be `0-9` instead of `1-9`):
[https://github.com/makesjs/makes/blob/9c771ba47a0f000d31269d8fba4b8cafa6d8ce0d/lib/skeleton-config.js#L11](https://github.com/makesjs/makes/blob/9c771ba47a0f000d31269d8fba4b8cafa6d8ce0d/lib/skeleton-config.js#L11)

**Comment by 3cp** [comment]
Thx. Looks like my fat finger error.
