### ISSUE TITLE
makes is broken on node v14, please update your dependencies

### ISSUE THREAD

**Issue by sspilleman** [huochunpeng/makes#8]
Hi,

If I try to create an aurelia project on node v14, its broken...
I get the following output:
```
<prompt> npx makes aurelia 
npx: installed 1 in 1.287s
makes v1.1.0 https://makes.js.org
[makes] Using remote skeleton github:aurelia/new
[makes] Fetching tarball https://codeload.github.com/aurelia/new/tar.gz/master
<prompt> 
```
So basically it stops execution......

If I clone your repo and update the dependencies and do a build and out that, it works again
I don't know exactly which dependency is giving troubles, I updated all to latest

So can you please update your dependencies?

Thanks!

**Comment by 3cp** [comment]
Thx! I will find out what caused that.

**Comment by sspilleman** [comment]
This project also has issues with npx/v14: https://github.com/facebook/create-react-app/issues/8896

**Comment by 3cp** [comment]
There is no major version change in deps, so I feel it's quite safe for me.

Added nodejs v14 in CI setup. Release a patch version built with latest deps.

Pls check if it works for you. I have not installed nodejs v14 yet (the binary built took too long).

**Comment by sspilleman** [comment]
Perfect! When will it be up you think?
brew installed it on macOS yesterday

**Comment by 3cp** [comment]
> Perfect! When will it be up you think?
> brew installed it on macOS yesterday

What do you mean? Npx makes is always running latest version of makes (already released). Nothing to do with brew.

**Comment by sspilleman** [comment]
Ok, great. I misunderstood your comment about CI and releasing a patch version.
Second comment was in response to your comment "I have not installed nodejs v14 yet (the binary built took too long)."

I just tested it.... It is not working :(. I'll have a look and get back to you

**Comment by 3cp** [comment]
I will try to install nodejs v14 then :-)

**Comment by sspilleman** [comment]
So this it the **current** result like before:
```
sander /tmp ➜ npx makes aurelia
npx: installed 1 in 1.879s
makes v1.1.2 https://makes.js.org
[makes] Using remote skeleton github:aurelia/new
[makes] Fetching tarball https://codeload.github.com/aurelia/new/tar.gz/master
sander /tmp ➜ 
```

Weird..... If I do this:
```bash
cd /tmp
npm install makes
cd node_modules
rm -rf makes
git clone https://github.com/makesjs/makes.git
cd makes
npm install
```
and then:
```
cd /tmp
npx makes aurelia
```
voila!
```
makes v1.1.2 https://makes.js.org
[makes] Using remote skeleton github:aurelia/new
[makes] Fetching tarball https://codeload.github.com/aurelia/new/tar.gz/master

         #
      ######   xxx
     ########  xxxx   ####         _                  _ _         ____
   x   ########    ########       / \  _   _ _ __ ___| (_) __ _  |___ \
     x  ######  #############    / _ \| | | | '__/ _ \ | |/ _` |   __) |
  xxxxx  ##  ###############    / ___ \ |_| | | |  __/ | | (_| |  / __/
   xxxxx  ###############      /_/   \_\__,_|_|  \___|_|_|\__,_| |_____|
    x ###############  xxx
    ##############  #   xx
 ##############  ######          https://aurelia.io
  ########## x  ########         https://github.com/aurelia
    #####  xxxx   ########       https://twitter.com/aureliaeffect
     #   x  x      ######
                     #

? Please name this new project: › my-app
```

**Comment by 3cp** [comment]
Probably a nodejs v14 issue (npx?), but I will test it out.

**Comment by 3cp** [comment]
Wait the code path is different, when you running locally, it's not using the build file, it's using the source file.

Edit `/tmp/node_modules/makes/bin/makes.js`

Change
```js
let makes;
try {
  // only for local source debug
  makes = require('../lib');
} catch (e) {
  // for production
  makes = require('../dist');
}
```

To
```js
let makes = require('../dist');
```

I bet you will see same issue. Must be some rollup result is not compatible with nodejs v14.

**Comment by sspilleman** [comment]
You're right, after this change it's broken again.
Quickly took a look @ the rollup repo, but there isn't an issue raised over there regarding v14.
I'll see if I can do some more digging to support you.

**Comment by 3cp** [comment]
Thanks very much for helping! I have no doubt this will be a hard piece.

**Comment by 3cp** [comment]
I will explore some alternatives like https://www.npmjs.com/package/npm-bundle (quite outdated).

**Comment by 3cp** [comment]
@bigopon suggested [ncc](https://github.com/zeit/ncc) which is seriously good for this task.

Can you try `npx makes@1.3.0 aurelia`? If it works, I will release it to latest dist-tag.

**Comment by 3cp** [comment]
You know what, I will just publish it to latest version, because there is no way to let me go back to rollup.

Pls reopen if this did not work.

**Comment by sspilleman** [comment]
It worked flawlessly! Thanks for your quick support!

**Comment by 3cp** [comment]
Great! Finally got ride of rollup for better.
